const appname = "Mart";
const appversion = "Version 1.0.0";
const credits = "@Abdalla Ayash";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Abdalla Ayash";
const passwordHint = "*******";
const forgetPassword = "Forget Passowrd?";
const login = "Login";
const signup = "Sign Up";
const createNewAccount = "or, create a new account";
const loginWith = "log in with";
const privacyPolicy = "Privacy Policy";
const terms = "Terms and Conditions";
const haveAccount = "Already Have An Account?";
const home = "Home";
const categories = "Categories";
const cart = "Cart";
const account = "Account";
const search = "Search anything...",
    todayDeal = "Today's Deal",
    flashSale = "Flash Sale",
    topBrand = "Top Brand",
    topSeller = "Top Sellers",
    topCategories = "Top Categories",
    featuredCategories = "Featured Categories";
